# Standard types:
# 
# primitives:
# bool, char, short, int, long, float, double
# uchar, ushort, uint, ulong,
# 
# string: string
# array: <type>[]
# 
# 
# Additional types may be declared in the types section:
# 
# [[types]]
# name = "test"         # name to use in the protocol definition
# cname = "t_test"      # name to use in the generated code
# type = "primitive"    # "primitive" or "structure"
# 
# 
# Models, requests and updates are declared in the
# corresponding sections as follows:
# 
# [[models]]           # "models", "requests" or "updates"
# name = "user"
# fields = [
#     { name = "id", type = "int" },
#     { name = "login", type = "string" },
#     { name = "avatar", type = "string" },
# ]
#
